#!/usr/bin/env bash
# this script is displaying "Best School" 10 times, with "hi" on th 9 time
msg="Best School"
count=0

while [ $count -lt 10 ]
do
if [ $count -eq 8 ]
then
echo -e "$msg/nHi"
else
echo "$msg"
fi

count=$((count+1))
done
